### ISSUE TITLE
problem building 

### ISSUE THREAD

**Issue by bagenal** [pn2200/g3data#1]
We have downloaded pn2200-g3data-v1.5.4-0-gb20c886.zip and tried to install on a Mac running 10.6.7.
When we did 
/opt/autoconf-2.66/bin/autoconf ./configure.ac
we got
configure.ac:10: error: possibly undefined macro: AM_SILENT_RULES
configure.ac:20: error: possibly undefined macro: AM_PROG_CC_C_O

which makes us think we are missing something in the download.

Also tried on a linux machine and found the same error.
Suggestions?
Thanks,
Fran

**Comment by pn2200** [comment]
As discussed in #8, to build from source you should invoke [autoreconf which invokes several tools](https://www.gnu.org/software/autoconf/manual/autoconf.html#autoreconf-Invocation) prior to building with ./configure && make.
