### ISSUE TITLE
How to Complete the Setup of Axis?

### ISSUE THREAD

**Issue by sami10007** [pn2200/g3data#7]
The system does not accept second click after setting Y2 axis point, only primary clicks. I cannot complete the setup of axes. 

Please, confirm if your version of g3data is the same as in apt-get. 

System: Ubuntu 16.04 64 bit   
Hardware: Macbook Air 2013-mid   
Releated thread: http://askubuntu.com/q/767982/25388

**Comment by sami10007** [comment]
I sent unsuccessfully to the author's email address. It seems that this project is depreciated it would be great to get a confirmation about it. I am discussing about it in the thread.

**Comment by pn2200** [comment]
There are two methods to set up the Y axis.

The first method is:

Press the button labeled "Set point Y1 on Y axis", then left-click (mouse button 1) on the image, then fill in the text box labeled "Y1 value". Then, press the button labeled "Set point Y2 on Y axis", then left-click on the image, then fill in the text box labeled "Y2 value".

The second method is:

Right-click (mouse button 3) on the image once to set the Y1 point on Y axis, then fill in the text box labeled "Y1 value". Then right-click (mouse button 3) on the image once to set the Y2 point on Y axis, then fill in the text box labeled "Y2 value".

The green T shapes mark the control points for the Y axis. There are equivalent purple T shapes to mark the control points for the X axis. The red squares are the actual data points you want to collect.

**Comment by sami10007** [comment]
Thank you! I managed to setup those successfully. 

There is something wrong in the application with my hardware 13". I see only the top part of the GUI. I cannot scroll the GUI. Is this a feature? This way, I cannot press extract those points.

**Comment by pn2200** [comment]
G3data has a fixed layout that can make it difficult to use on a small screen. The workaround you have found (disabling parts of the view) is one way to make it easier to use.
