### ISSUE TITLE
autotools issue - had to create an empty config.h.in to get it to build on CENTOS 7

### ISSUE THREAD

**Issue by tunaboy** [pn2200/g3data#8]
Absolutely love this code, and use it a fair amount.  It no longer resides in Centos/EPEL as of 7, as far as I can see, so I cloned the repository, and then had issues getting the build to work.  

Very small issue, but I had to create a zero length config.h.in for the autotools process to work.  Then it worked like a charm, and I've got g3data available for my Centos7 installation.

Small issue, quickly fixed, but thought I'd save others some time when they have to build from here.  

Thanks much,
Mike

**Comment by pn2200** [comment]
My understanding is that config.h.in is created automatically by invoking autoheader, so there shouldn't be a need for an empty file. When building from source, I usually invoke the following sequence to rebuild everything:
```
autoreconf -fiv
./configure
make
```

[autoreconf invokes several tools](https://www.gnu.org/software/autoconf/manual/autoconf.html#autoreconf-Invocation) including autoheader. How are you rebuilding? I could add a blank config.h.in but I don't think it is necessary.

**Comment by tunaboy** [comment]
Also, the INSTALL assumes that configure has already been created, which is where the autotools part comes from(which ends up in a working configure script).  May want to add that part to the Installs bit.

I believe the process (which works if there is an empty config.h.in file) is

aclocal
automake
autoconf

I believe at the end of this, you have a working configure script, and all else follows....

Cheers all, and thanks again pn2200
Mike

**Comment by tunaboy** [comment]
So, if I start from scratch, I can do this, but it does involve your invocation of the autotools, which I just learned from you.  My autotools may be outdated, but I think I'd add your recipe:

    autoreconf -fiv
    ./configure
    make

to the README or INSTALL file.  

Also, the comment I apparently just added a few minutes ago was one I thought I'd added in my original posting, sorry.  Not sure why that didn't post the first time, and magically did this time.

Thanks much,
Mike

**Comment by tunaboy** [comment]
And now I think I've deleted the extraneous post that I thought I'd done as an addendum to my original post...

Mike

**Comment by pn2200** [comment]
I added instructions on building from source in 6c9df0e4a333245fe1ce4cb4059b10179026a768.
